(function(g){var window=this;var g4=function(a){var b={languageCode:a.A,languageName:a.B,displayName:g.KO(a),kind:a.C,name:a.D,id:a.Ja,is_servable:a.G,is_default:a.isDefault,is_translateable:a.H,vss_id:a.F};a.o&&(b.translationLanguage=a.o);return b},h4=function(a){return a.o?a.o.languageCode:a.A},nDa=function(a,b){var c=new g.JO;
c.A=a.A;c.B=a.B;c.D=a.D;c.C=a.C;c.isDefault=!1;c.G=a.G;c.H=a.H;c.F=a.F;c.J=a.J;c.o=b;return c},oDa=function(){this.A=[];
this.o=[]},i4=function(a,b){return b?a.o.concat(a.A):a.o},j4=function(a,b){switch(b.C){case "asr":var c=a.A;
g.Va(c,(0,g.B)(b.Vv,b))||c.push(b);break;default:c=a.o,g.Va(c,(0,g.B)(b.Vv,b))||c.push(b)}},k4=function(){g.L.call(this);
this.A=new oDa;this.D=[]},l4=function(a,b,c){k4.call(this,a);
this.o=null;this.D=b.iA;this.C=c},m4=function(){this.ub=[]},n4=function(a,b,c,d,e,f){g.L.call(this);
this.L=a;this.B=b;this.F=new m4;this.o=null;this.J=d;this.M=f;this.A=this.C=null;this.H=c;this.G=e||!1;this.K=new g.V(this.DC,1E3,this);g.M(this,this.K);this.D=new g.vH(this);g.M(this,this.D);g.Y(b).experiments.o("html5_disable_captions_seek_complete")?this.D.R(b,"seekto",this.oD):this.D.R(b,"seekcomplete",this.GO);this.oD(b.getCurrentTime());this.DC()},o4=function(a,b){b-=a.B.Vc();
var c=a.o;a.o=g.Sa(a.H.Ng(b).o);c!=a.o&&a.M&&a.M()},pDa=function(a,b){var c=g.bL(b,a.L,{}).Wa(),d={format:"RAW",
withCredentials:!0};a.G&&(d.responseType="arraybuffer");a.A=g.HG(c,d,3,100).then((0,g.B)(a.nT,a));a.C=b;c=a.F;d=a.C.o[0].A;var e=g.rb(c.ub,d);0<=e||0>e&&1==(-e-1)%2||(e=-e-1,0<e&&1==d-c.ub[e-1]&&e<c.ub.length&&1==c.ub[e]-d?(g.db(c.ub,e),g.db(c.ub,e-1)):0<e&&1==d-c.ub[e-1]?c.ub[e-1]=d:e<c.ub.length&&1==c.ub[e]-d?c.ub[e]=d:(g.nb(c.ub,e,0,d),g.nb(c.ub,e+1,0,d)))},p4=function(a,b){k4.call(this,g.Y(b));
this.o=a;this.G=b;this.C=null;this.B=!1;this.F=g.wO(g.Y(this.G))&&!this.o.A},qDa=function(a,b){var c=[],d;
for(d in a.o.o){var e=a.o.o[d];if(g.PX(e,b||null)){var f="en",k="English",l=".en",m="";if(e=e.info.captionTrack)f=e.languageCode,k=e.displayName,l=e.vssId,m=e.kind;c.push(new g.JO({id:d,languageCode:f,languageName:k,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},rDa=function(a,b){return null!=b&&b in a.o.o?a.o.o[b]:null},sDa=function(a,b,c){var d=[],e;
for(e in a.o.o){var f=a.o.o[e];if(g.PX(f,c||null)){var k=f.info.captionTrack;k&&k.languageCode==b&&d.push(f)}}return d.length?d[0]:null},q4=function(a,b,c,d,e){k4.call(this,e||null);
c=c||g.OF(a).hl||"";c=c.split("_").join("-");this.B=g.QF(a,{hl:c});this.C=b;this.F=!!d;this.G={};this.o=null},r4=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.jR.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.D=f;this.A=k},s4=function(a,b,c,d,e){g.jR.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.A=[]},tDa=function(a){a=void 0===a?{}:a;
var b="_"+t4++;return new s4(0,0x8000000000000,0,b,a)},u4=function(a,b,c,d,e,f){var k={};
g.Oa(k,b);g.Oa(k,a.params);g.Oa(k,c);var l={};g.Oa(l,b.Ub);a.params.Ub&&g.Oa(l,a.params.Ub);g.Oa(l,c.Ub);k.Ub=l;g.W.call(this,{I:"div",N:"caption-window",T:{id:"caption-window-"+a.id,dir:1==k.ug?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:k.lang},O:[{I:"span",N:"captions-text"}]});this.G=[];this.Y=!1;this.D=a;this.ba=this.aa=null;this.Sa=e;this.Oa=f;this.K=null;this.ha=.96*e;this.xa=.96*f;this.B=k;this.Ma=c;this.F=this.o["captions-text"];this.Ga=null!=this.F.style["box-decoration-break"]||
null!=this.F.style["-webkit-box-decoration-break"];this.ea=d/360*16;this.type=0;this.ma=this.ea*uDa(l);a=new g.CH(this.element,!0);g.M(this,a);a.subscribe("dragstart",this.FO,this);a.subscribe("dragmove",this.EO,this);a.subscribe("dragend",this.DO,this);this.ya=this.ua=0;b="";this.B.windowOpacity&&(a=g.Wu(this.B.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.B.windowOpacity+")");a={"background-color":b,display:!1===this.B.isVisible?"none":"","text-align":vDa[this.B.textAlign]};this.Ga&&(a["border-radius"]=
b?this.ma/8+"px":"");if(this.H=2==this.D.params.ug||3==this.D.params.ug)b=this.element,c="vertical-rl",1==this.B.kG&&(c="vertical-lr"),g.ee&&(c="vertical-lr"==c?"tb-lr":"tb-rl"),g.Yh(b,"-o-writing-mode",c),g.Yh(b,"-webkit-writing-mode",c),g.Yh(b,"writing-mode",c),g.Yh(b,"text-orientation","upright"),g.T(b,"ytp-vertical-caption"),3==this.D.params.ug&&(g.Yh(b,"text-orientation",""),g.Yh(b,"transform","rotate(180deg)"));g.Yh(this.element,a);switch(this.B.kh){case 0:case 1:case 2:g.T(this.element,"ytp-caption-window-top");
break;case 6:case 7:case 8:g.T(this.element,"ytp-caption-window-bottom")}},uDa=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0==a.offset||2==a.offset)b*=.8;return b},v4=function(a,b){var c={},d=b.background?b.background:a.B.Ub.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.B.Ub.backgroundOpacity;d=g.Wu(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Ga&&(c["box-decoration-break"]="clone",c["border-radius"]=a.ma/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.ea*uDa(b)+"px";d=1;e=b.color||a.B.Ub.color;if(b.color||null!=b.textOpacity)e=g.Wu(e),d=null==b.textOpacity?a.B.Ub.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;0==f&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";b.qA&&(k=e=b.qA);var l=a.ea/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),q=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=q;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.nG()?
'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.B.Ub.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7==b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.eg&&(c["font-style"]="italic");
b.underline&&(c["text-decoration"]="underline");b.RL&&(c.visibility="hidden");return c},wDa=function(a){a.K=g.le("SPAN");
g.T(a.K,"caption-visual-line");a.F.appendChild(a.K)},xDa=function(a,b){var c=g.le("SPAN");
g.Yh(c,v4(a,b));c.classList.add("ytp-caption-segment");a.K.appendChild(c);c.previousElementSibling&&(g.Yh(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.Yh(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},yDa=function(a,b,c){a.Y=a.Y||!!c;
var d={};g.Oa(d,a.B.Ub);g.Oa(d,c||b.A);g.Oa(d,a.Ma.Ub);var e=!a.K;e&&wDa(a);c=a.aa&&a.ba&&g.hc(d,a.ba)?a.aa:xDa(a,d);for(var f=g.x(b.text),k=f?b.text.split("\n"):[b.text],l=0;l<k.length;l++){var m=0<l||!b.D,n=k[l];m&&!e?(wDa(a),c=xDa(a,d)):m&&e&&(e=!1);n&&c.appendChild(f?g.me(n):n)}if(!f)for(e=b.text.querySelectorAll("RT".toString()),f=0;f<e.length;f++)g.Yh(e[f],v4(a,d)),g.Yh(e[f],"font-size","50%");a.ba=d;a.aa=c;a.G.push(b)},zDa=function(){},x4=function(){this.B=this.A=this.mode=this.C=0;
this.D=new w4(this);this.F=new w4(this);this.o=[];this.clear()},BDa=function(a,b,c){if(255==a&&255==b||!a&&!b)return{Qo:a,
Ro:b,result:0};a=ADa[a];b=ADa[b];if(a&128){if(!(b&128)&&0!=c.o&&c.A==b)return{Qo:a,Ro:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Qo:a,Ro:b,result:2};return{Qo:a,Ro:b,result:3}},DDa=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.B&&a.reset(),a.D.o.clear(),a.F.o.clear()):(a.B=0,CDa(a.D,b,c,d))},EDa=function(a,b){a.o.sort(function(e,f){var k=e.time-f.time;
return 0==k?e.order-f.order:k});
for(var c=0;c<a.o.length;c++){var d=a.o[c];a.A=d.time;0==d.type?DDa(a,d.lA,d.mA,b):1==d.type&&a.C&496&&CDa(a.F,d.lA,d.mA,b)}a.o.length=0},y4=function(){this.o=0},z4=function(){this.A=this.C=this.o=0},A4=function(){this.timestamp=this.Je=0},B4=function(a){this.C=[];
for(var b=0;15>=b;b++){this.C[b]=[];for(var c=0;32>=c;c++)this.C[b][c]=new A4}this.o=this.A=this.row=0;this.style=new y4;this.D=a;this.B=0},C4=function(a,b){if(3==a.style.o){for(var c=0,d=0,e=a.D.A+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var q=a.C[m][p];
if(0!=q.Je){0==c&&(c=m,d=p);n=String.fromCharCode(q.Je);var u=q.timestamp;u<e&&(e=u);q.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==q.Je||32==p)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.D(c,d,e,l,f)}else for(d=c=0,f=e=a.D.A+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(p=a.C[k][m],q=p.Je,0!=q&&(0==c&&(c=k,d=m),n=String.fromCharCode(q),u=p.timestamp,u<=e&&(e=u),l+=n,p.reset()),32==m||0==q)l&&b.D(c,d,e,f,l),e=f,l="",d=c=0},JDa=function(a,b){switch(a){case 0:return FDa[(b&127)-32];
case 1:return GDa[b&15];case 2:return HDa[b&31];case 3:return IDa[b&31]}return 0},D4=function(a){return a.C[a.row][a.A]},E4=function(a,b,c){2<=b&&1<a.A&&(--a.A,D4(a).Je=0);
var d=D4(a);d.timestamp=a.D.A+0;d.Je=JDa(b,c);32>a.A&&a.A++},KDa=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.C[b+e][f].rh(a.C[c+e][f])},F4=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.C[b+d][e].reset()},G4=function(a){a.row=0<a.o?a.o:1;
a.A=1;F4(a,0,15)},H4=function(a){this.B=a;
this.D=0;this.style=new y4;this.F=new B4(a);this.G=new B4(a);this.H=new B4(a);this.A=this.F;this.C=this.G;this.o=this.A},I4=function(a,b,c){var d=a.A,e=!1;
switch(a.style.get()){case 4:if(0<d.o)break;case 1:case 2:C4(d,c),G4(a.A),G4(a.C),d.row=15,d.o=b,e=!0}a.style.set(3);a.o=d;a.o.style=a.style;a.B.mode=1<<d.B;e?d.A=1:d.o!=b&&(d.o>b?(C4(d,c),F4(d,d.row-d.o,b)):d.row<b&&(b=d.o),d.o=b)},LDa=function(a){a.style.set(1);
a.o=a.C;a.o.o=0;a.o.style=a.style;a.B.mode=1<<a.o.B},MDa=function(a){a.style.set(4);
a.o=a.H;a.o.style=a.style;a.B.mode=1<<a.o.B},w4=function(a){this.A=a;
this.o=new z4;this.D=0;this.C=new H4(a);this.F=new H4(a);this.B=this.C},CDa=function(a,b,c,d){a.o.update();
b=BDa(b,c,a.o);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Qo;c=b.Ro;if(32<=e||!e)a.A.mode&a.A.C&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.B.o,b&96&&E4(a,0,b),c&96&&E4(a,0,c),0!=b&&0!=c&&3==a.style.o&&C4(a,d));else if(e&16)a:if(!a.o.matches(e,c)&&(b=a.o,b.C=e,b.A=c,b.o=2,b=e&8?a.F:a.C,a.B=b,a.A.mode=1<<(a.D<<2)+(b.D<<1)+(4==b.style.o?1:0),(a.A.mode|1<<(a.D<<2)+(b.D<<1)+(4!=b.style.o?1:0))&a.A.C))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&14)>>1):
0;c=b.o;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!=c.row){if(d<c.o&&(d=c.o,d==c.row))break;var f=1+c.row-c.o,k=1+d-c.o;KDa(c,k,f,c.o);b=f;e=c.o;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));F4(c,b,e)}}c.row=d;c.A=a+1}else switch(e&7){case 1:switch(c&112){case 32:E4(b.o,0,32);break a;case 48:57==c?(d=b.o,D4(d).Je=0,32>d.A&&d.A++):E4(b.o,1,c&15)}break;case 2:c&32&&E4(b.o,2,c&31);break;case 3:c&32&&E4(b.o,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:LDa(b);break;
case 33:d=b.o;1<d.A&&(--d.A,D4(d).Je=0);break;case 36:d=b.o;b=D4(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.C[a][c]==b){for(;32>=c;c++)d.C[a][c].reset();break}break;case 37:I4(b,2,d);break;case 38:I4(b,3,d);break;case 39:I4(b,4,d);break;case 40:E4(b.o,0,32);break;case 41:b.style.set(2);b.o=b.A;b.o.o=0;b.o.style=b.style;b.B.mode=1<<b.o.B;break;case 42:d=b.H;d.o=15;d.style.set(4);G4(d);MDa(b);break;case 43:MDa(b);break;case 44:a=b.A;switch(b.style.get()){case 1:case 2:case 3:C4(a,d)}F4(a,0,15);break;
case 45:b:{a=b.o;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.A=1;break b}case 3:}2>a.o&&(a.o=2,a.row<a.o&&(a.row=a.o));b=a.row-a.o+1;C4(a,d);KDa(a,b,b+1,a.o-1);F4(a,a.row,1)}break;case 46:F4(b.C,0,15);break;case 47:C4(b.A,d),b.C.updateTime(b.B.A+0),d=b.C,b.C=b.A,b.A=d,LDa(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.o,32<(d.A+=c&3)&&(d.A=32)}}},J4=function(a){g.L.apply(this,arguments)},K4=function(a){J4.call(this);
this.C={};this.J={};this.K={};this.D="_"+t4++;this.F=a;this.H={};this.A=this.o=null;this.G=!0},L4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return parseFloat(c)},M4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},N4=function(a,b){var c=L4(a,b);
return void 0!=c?c:null},P4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return O4.test(c),c},NDa=function(a,b){var c={},d=b.getAttribute("ws");
g.Oa(c,d?a.K[d]:a.F);d=N4(b,"mh");null!=d&&(c.Qv=d);d=N4(b,"ju");null!=d&&(c.textAlign=d);d=N4(b,"pd");null!=d&&(c.ug=d);d=N4(b,"sd");null!=d&&(c.kG=d);d=P4(b,"wfc");null!=d&&(c.windowColor=d);d=L4(b,"wfo");void 0!=d&&(c.windowOpacity=d/255);return c},ODa=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Oa(c,a.J[d]);d=N4(b,"ap");null!=d&&(c.kh=d);d=L4(b,"cc");null!=d&&(c.ep=d);d=L4(b,"ah");null!=d&&(c.fg=d);d=L4(b,"rc");null!=d&&(c.Mn=d);d=L4(b,"av");null!=d&&(c.fi=d);return c},PDa=function(a,b,c,d){var e={};
g.Oa(e,ODa(a,b));g.Oa(e,NDa(a,b));d?g.hc(e,a.F)?(d=a.D,e=a.F):d="_"+t4++:d=b.getAttribute("id")||"_"+t4++;a=L4(b,"t")+c;b=L4(b,"d")||0x8000000000000;if(2==e.ug||3==e.ug)c=e.Mn,e.Mn=e.ep,e.ep=c;return new s4(a,b,0,d,e)},Q4=function(a,b,c,d,e,f,k){u4.call(this,a,b,c,d,e,f,k);
this.type=1},R4=function(a,b,c){this.G=c;
this.version=this.F=this.B=this.o=0;this.A=new DataView(a);this.C=[]},S4=function(a){var b=a.o;
a.o+=1;return a.A.getUint8(b)},T4=function(a){var b=a.o;
a.o+=4;return a.A.getUint32(b)},U4=function(a,b){J4.call(this);
this.A=a;this.track="CC3"==b.B?4:0;this.o=new x4;this.o.C=1<<this.track},RDa=function(a){if(g.x(a))return!1;
a=new R4(a,8,0);return QDa(a)},QDa=function(a){if(!(a.o<a.A.byteLength)||1380139777!=T4(a))return!1;
a.version=S4(a);if(1<a.version)return!1;S4(a);S4(a);S4(a);return!0},V4=function(a,b,c,d,e,f,k){u4.call(this,a,b,c,d,e,f,k);
g.T(this.element,"ytp-caption-window-rollup");this.type=2;this.J=[];this.M=this.L=this.ia=0;this.P=NaN;this.za=0;this.Ia=null;this.ka=new g.V(this.sT,433,this);g.M(this,this.ka)},SDa=function(a,b){return(a.H?b.offsetHeight:b.offsetWidth)+1},TDa=function(a){if(isNaN(a.P)){var b=a.B.ep;
if(b){var c=g.le("SPAN");g.ze(c,"\u2013".repeat(b));g.Yh(c,v4(a,a.B.Ub));a.F.appendChild(c);a.P=c.offsetWidth;a.F.removeChild(c)}else a.P=0}return a.P},UDa=function(a,b){if(!b)return"";
a.H&&1!=a.D.params.kG&&(b*=-1);return"translate"+(a.H?"X":"Y")+"("+b+"px)"},VDa=function(a){a.J=[].concat(g.ea(document.getElementsByClassName("caption-visual-line")));
for(var b=a.D.params.Mn,c=0,d=0,e=a.J.length-1;c<b&&-1<e;){var f=a.J[e];d+=a.H?f.offsetWidth:f.offsetHeight;c++;e--}a.J.length<b&&(d*=b/a.J.length);a.L=d;a.M=Math.max(TDa(a),a.za,SDa(a,a.F))},WDa=function(a,b){VDa(a);
var c=a.J.reduce(function(e,f){return(a.H?f.offsetWidth:f.offsetHeight)+e},0);
c=a.L-c;if(c!=a.ia){var d=0<c&&0==a.ia;b||isNaN(c)||d||(g.T(a.element,"ytp-rollup-mode"),g.Dv(a.ka));g.Yh(a.F,"transform",UDa(a,c));a.ia=c}VDa(a)},W4=function(){J4.call(this)},XDa=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.eg=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var p=k.childNodes[n];if(3==p.nodeType){p=new r4(b,c,d,e.id,p.nodeValue,f||0<n,g.dc(l)?void 0:l);m.push(p);var q=e;g.M(q,p);q.A.push(p)}else q={},g.Oa(q,l),XDa(a,b,c,d,e,!0,p,q,m)}},X4=function(a){var b=0;
a=g.r(a.split(":"));for(var c=a.next();!c.done;c=a.next())b=60*b+parseFloat(c.value);return 1E3*b},YDa=function(a,b,c,d){d=Object.assign({Qv:0},d);
return new s4(a,b,c,"_"+t4++,d)},Y4=function(a){g.L.call(this);
this.A=a;this.o=null},a5=function(a){g.kV.call(this,a);
this.D=g.Y(a);this.C=a.getVideoData();this.xa=g.OU(a);this.L=a;var b=null,c=g.OE("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.xE(c));this.ba=b;this.B={Ub:{}};this.F={Ub:{}};this.K=[];this.W={};this.aa={};this.M=!1;this.ua=g.Yua(this.C,this.L);this.za=!!this.C.captionTracks.length;this.Ga=!!this.C.Pl;this.ma="3"==this.D.C;b=g.cV(a);c=!(!b||!b.ao());this.ya=!(!b||!b.wj());this.G=this.ma&&c&&!this.ua;this.Y=!this.G&&this.ma&&this.ya&&this.ua;this.A=this.H=this.J=this.P=this.ka=null;this.ga=
new Y4(this.D);g.M(this,this.ga);c=b=this.o=null;this.G||(b=new g.Av(this.zG,void 0,this),g.M(this,b),c=new g.V(this.fV,2E3,this),g.M(this,c));this.ea=b;this.ia=c;this.Z=new g.vH(this);g.M(this,this.Z);this.G||this.Z.R(a,"resize",this.ay);this.Z.R(a,"onPlaybackAudioChange",this.uQ);this.Z.R(a,g.lR("captions"),this.MN,this);this.Z.R(a,"crx_captions",this.NN,this);Z4(this,$4(this,"display-settings")||{})},ZDa=function(a){if(1==a.D.oh||1==a.C.oh||"alwayson"==g.NP(a.C,"yt:cc"))return!0;
if(2==a.D.oh){var b=$4(a,"module-enabled");if(null!=b)return!!b}if(a.C.captionTracks.length)var c=a.player.getAudioTrack().Et;return"ON"==c||"on"==g.NP(a.C,"yt:cc")},b5=function(a,b){if(a.o&&(void 0===b||!b)||!a.C.captionTracks.length)return!1;
var c=a.player.getAudioTrack();return!!c.xp||"FORCED_ON"==c.Et},d5=function(a,b){if(a.A){if(a.H&&a.H.o)return a.H.o;
var c=b;c||(c=a.Ga?!1:a.za?!1:!0);c=i4(a.A.A,c);for(var d=[a.C.nh,a.D.nh,g.NP(a.C,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(h4(c[f])==d[e])return c[f];return a.H&&a.H.Wt?a.H.Wt:(d=c.find(function(k){return k.isDefault}))?d:c[0]||c5(a)}return null},c5=function(a){return a.H&&a.H.xp},e5=function(a){var b=c5(a);
return!!b&&a.o==b},$Da=function(a,b){for(var c=g.cV(a.L).sa().textTracks,d=a.o.toString(),e=0;e<c.length;e++){var f=c[e];
f.id==d&&(b?"showing"!=f.mode&&(f.mode="showing"):"showing"==f.mode&&(f.mode="disabled"))}},g5=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.M=c,a.M&&f5(a,"module-enabled",!!b));a.o=b;b5(a)&&(a.o=c5(a));a.load()},aEa=function(a,b){var c=a.xa.getVideoContentRect(!0).height;
if(!c)return null;var d=a.xa.getPlayerSize();switch(null!=b.params.Qv?b.params.Qv:1<b.A.length?1:0){case 1:return new Q4(b,a.B,a.F,c,d.width,d.height,a.D.experiments);case 2:return new V4(b,a.B,a.F,c,d.width,d.height,a.D.experiments);default:return new u4(b,a.B,a.F,c,d.width,d.height,a.D.experiments)}},Z4=function(a,b,c){var d=h5.Ub;
a.B={};g.Oa(a.B,h5);a.B.Ub={};g.Oa(a.B.Ub,d);a.F={Ub:{}};var e=b.backgroundOverride?a.F:a.B,f=b.background||d.background;O4.test(f);e.Ub.background=f;e=b.colorOverride?a.F:a.B;f=b.color||d.color;O4.test(f);e.Ub.color=f;e=b.windowColorOverride?a.F:a.B;f=b.windowColor||h5.windowColor;O4.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.F:a.B;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.Ub.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.F:a.B;f=b.fontSizeIncrement;null==f&&(f=d.fontSizeIncrement);
e.Ub.fontSizeIncrement=f;f=b.fontStyleOverride?a.F:a.B;e=b.fontStyle;null==e&&(e=d.bold&&d.eg?3:d.bold?1:d.eg?2:0);f=f.Ub;switch(e){case 1:f.bold=!0;delete f.eg;break;case 2:delete f.bold;f.eg=!0;break;case 3:f.bold=!0;f.eg=!0;break;default:delete f.bold,delete f.eg}e=b.textOpacityOverride?a.F:a.B;f=b.textOpacity;null==f&&(f=d.textOpacity);e.Ub.textOpacity=f;e=b.windowOpacityOverride?a.F:a.B;f=b.windowOpacity;null==f&&(f=h5.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?a.F:a.B;f=b.charEdgeStyle;
null==f&&(f=d.charEdgeStyle);e.Ub.charEdgeStyle=f;e=b.fontFamilyOverride?a.F:a.B;f=b.fontFamily;null==f&&(f=d.fontFamily);e.Ub.fontFamily=f;a.loaded&&a.ay();c&&f5(a,"display-settings",b)},cEa=function(a,b){if(b&&!a.J){var c=tDa({ug:0,
lang:"en"});a.J=[c,new r4(c.start,c.end-c.start,0,c.id,"Captions look like this")];g.XU(a.player,a.J)}else!b&&a.J&&(bEa(a,a.J),a.J=null)},bEa=function(a,b){g.ZU(a.player,b);
(0,g.E)(b,function(c){g.eb(this.K,c)},a);
a.ea.dk()},$4=function(a,b){if(!a.ba)return null;
try{var c=a.ba.get(b)}catch(d){a.ba.remove(b)}return c},f5=function(a,b,c){if(a.ba)try{a.ba.set(b,c)}catch(d){}};
g.sR.prototype.Ql=g.ca(12,function(){for(var a=g.Yd(document,"track",void 0,this.o),b=0;b<a.length;b++)g.re(a[b])});
g.T_.prototype.Ql=g.ca(11,function(){this.o.Ql()});
g.sR.prototype.ao=g.ca(10,function(){return!!this.o.textTracks});
g.T_.prototype.ao=g.ca(9,function(){return this.o.ao()});
g.sR.prototype.Kl=g.ca(8,function(a){for(var b=0;b<a.length;b++)this.o.appendChild(a[b])});
g.T_.prototype.Kl=g.ca(7,function(a){this.o.Kl(a)});
g.yQ.prototype.wj=g.ca(6,function(){});
g.sR.prototype.wj=g.ca(5,function(){return!(!this.o.textTracks||!this.o.textTracks.addEventListener)});
g.T_.prototype.wj=g.ca(4,function(){return this.o.wj()});
g.JO.prototype.Vv=g.ca(2,function(a){return a?this.toString()==a.toString():!1});
g.UI.prototype.Jp=g.ca(1,function(a){return(a=this.th(a))?a.A:0});
g.ML.prototype.Jp=g.ca(0,function(){return 0});
var dEa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,O4=/^#(?:[0-9a-f]{3}){1,2}$/i;g.t(k4,g.L);k4.prototype.lF=function(){return!1};
k4.prototype.V=function(){this.gi();g.L.prototype.V.call(this)};
g.t(l4,k4);l4.prototype.Lv=function(a,b,c){b=this.Am(a,b);var d=(0,g.B)(function(e){this.o=null;c(e.responseText,a)},this);
this.gi();this.o=g.fG(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
l4.prototype.Mv=function(a){if(this.C)for(var b=g.r(this.C.captionTracks),c=b.next();!c.done;c=b.next())j4(this.A,c.value);a()};
l4.prototype.Am=function(a,b){var c=a.Wa(),d={fmt:b};a.o&&(d.tlang=h4(a));return g.QF(c,d)};
l4.prototype.gi=function(){this.o&&this.o.abort()};
m4.prototype.contains=function(a){a=g.rb(this.ub,a);return 0<=a||0>a&&1==(-a-1)%2};
m4.prototype.length=function(){return this.ub.length/2};
g.t(n4,g.L);g.h=n4.prototype;g.h.V=function(){g.L.prototype.V.call(this);this.A&&this.A.cancel()};
g.h.oD=function(a){var b=this;if(this.H.Ti())var c=this.D.R(this.B,"progresssync",function(){b.H.index.Jb()&&(b.reset(),b.o=null,o4(b,b.B.getCurrentTime()),b.D.Ka(c))});
else o4(this,a)};
g.h.GO=function(){o4(this,this.B.getCurrentTime())};
g.h.reset=function(){this.F=new m4;this.A&&(this.A.cancel(),this.A=null)};
g.h.DC=function(){var a;if(a=null!==this.o)a=this.o,a=a.o.Vg(a);!a||this.A||this.o&&30<this.o.startTime-this.B.getCurrentTime()||(a=this.o,a=a.o.Ck(a),a.o[0].duration&&(this.F.contains(a.o[0].A)||pDa(this,a),this.o=g.Sa(a.o)));this.K.start()};
g.h.nT=function(a){var b=!(this.G?a.response:a.responseText)||400<=a.status,c=g.TL(a);c?(a=g.bL(this.C,this.L,{}),b=this.C,g.XK(b.A,a,c),b.requestId=a.get("req_id"),pDa(this,this.C)):(b||null===this.J||(this.G?this.J(a.response,1E3*(this.C.o[0].startTime+this.B.Vc())):this.J(a.responseText,1E3*(this.C.o[0].startTime+this.B.Vc()))),this.A=this.C=null)};
g.t(p4,k4);g.h=p4.prototype;g.h.Lv=function(a,b,c){this.gi();b=rDa(this,a.getId());b||(b=a.A,b=this.o.A?sDa(this,b,"386"):sDa(this,b));if(b){var d=1E3*(b.index.Jp(b.index.uf())-b.index.ld(b.index.uf()));this.C=new n4(new g.tK,this.G,b,function(e,f){c(e,a,f,d)},this.F||g.lK(b.info),(0,g.B)(function(){this.C&&this.C.reset();
this.B=!0},this))}};
g.h.lF=function(){var a=this.B;this.B=!1;return a};
g.h.Mv=function(a){var b;this.F?b=[new g.JO({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.JO({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:b=this.o.A?qDa(this,"386"):qDa(this);b=g.r(b);for(var c=b.next();!c.done;c=b.next())j4(this.A,c.value);a()};
g.h.gi=function(){this.C&&(this.C.dispose(),this.C=null)};
g.h.Am=function(){return""};
g.t(q4,k4);q4.prototype.Lv=function(a,b,c){b=this.Am(a,b);var d=(0,g.B)(function(e){this.o=null;c(e.responseText,a)},this);
this.gi();this.o=g.fG(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
q4.prototype.Mv=function(a){var b=this.B,c={type:"list",tlangs:1,v:this.C,vssids:1};this.F&&(c.asrs=1);b=g.QF(b,c);c=(0,g.B)(function(d){this.o=null;if((d=d.responseXML)&&d.firstChild){for(var e=g.r(d.getElementsByTagName("track")),f=e.next();!f.done;f=e.next()){var k=f.value;f=k.getAttribute("lang_code");var l=k.getAttribute("lang_translated"),m=k.getAttribute("name"),n=k.getAttribute("kind"),p=k.getAttribute("id"),q="true"==k.getAttribute("lang_default"),u="true"==k.getAttribute("cantran");k=k.getAttribute("vss_id");
j4(this.A,new g.JO({languageCode:f,languageName:l,name:m,kind:n,id:p,is_servable:!0,is_translateable:u,vss_id:k,is_default:q}))}d=d.getElementsByTagName("target");e=d.length;for(f=0;f<e;f++)l=d[f].getAttribute("lang_code"),m=d[f].getAttribute("lang_translated"),n=d[f].getAttribute("lang_original"),p=d[f].getAttribute("id"),q="true"==d[f].getAttribute("lang_default"),l={languageCode:l,languageName:m,languageOriginal:n,id:p,isDefault:q},this.G[l.languageCode]=l.languageName,this.D.push(l)}a()},this);
this.gi();this.o=g.fG(b,{format:"RAW",onSuccess:c,withCredentials:!0})};
q4.prototype.Am=function(a,b){var c=this.B,d={v:this.C,type:"track",lang:a.A,name:a.getName(),kind:a.C,fmt:b};a.o&&(d.tlang=h4(a));return c=g.QF(c,d)};
q4.prototype.gi=function(){this.o&&this.o.abort()};var vDa=["left","right","center","justify"];var h5={windowColor:"#080808",windowOpacity:0,textAlign:2,kh:7,fg:50,fi:100,Ub:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.t(r4,g.jR);r4.prototype.toString=function(){return g.jR.prototype.toString.call(this)};g.t(s4,g.jR);s4.prototype.toString=function(){return g.jR.prototype.toString.call(this)};
var t4=0;g.t(u4,g.W);g.h=u4.prototype;g.h.FO=function(a,b){var c=g.ni(this.element,this.element.parentElement);this.ua=a-c.x;this.ya=b-c.y;g.T(this.element,"ytp-dragging")};
g.h.EO=function(a,b){var c=g.qi(this.element),d=a-this.ua-.02*this.Sa,e=b-this.ya-.02*this.Oa,f=(d+c.width/2)/this.ha*3;f=Math.floor(g.Kd(f,0,2));var k=(e+c.height/2)/this.xa*3;k=Math.floor(g.Kd(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.ha;d=100*g.Kd(d,0,1);c=(e+k/2*c.height)/this.xa;c=100*g.Kd(c,0,1);this.D.params.kh=l;this.D.params.fi=c;this.D.params.fg=d;this.B.kh=l;this.B.fi=c;this.B.fg=d;this.AF()};
g.h.DO=function(){g.Mr(this.element,"ytp-dragging")};
g.h.AF=function(){this.tj(this.G)};
g.h.Zb=function(){return this.type};
g.h.tj=function(a){var b=Math.min(this.tB(),this.ha),c=this.sB(),d="";3==this.D.params.ug&&(d="rotate(180deg)");g.Yh(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.kt(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.B.fg+2;d=this.B.kh;switch(d){case 0:case 3:case 6:a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.F.offsetWidth;
b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.B.fi+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.Yh(this.element,a)};
g.h.kt=function(a){var b;for(b=0;b<a.length&&a[b]==this.G[b];b++);if(this.Y||this.G.length>b)b=0,this.Y=!1,this.G=[],this.K=this.ba=this.aa=null,g.pe(this.F);for(;b<a.length;b++)yDa(this,a[b])};
g.h.tB=function(){return 0};
g.h.sB=function(){return 0};
g.h.toString=function(){return g.W.prototype.toString.call(this)};zDa.prototype.D=function(){};x4.prototype.clear=function(){this.B=this.A=this.mode=0;this.o=[];this.reset()};
x4.prototype.reset=function(){this.mode=0;this.D.reset(0);this.F.reset(1)};
var ADa=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];y4.prototype.set=function(a){this.o=a};
y4.prototype.get=function(){return this.o};
z4.prototype.clear=function(){this.o=0};
z4.prototype.update=function(){this.o=2==this.o?1:0};
z4.prototype.matches=function(a,b){return 0!=this.o&&a==this.C&&b==this.A};
A4.prototype.rh=function(a){this.Je=a.Je;this.timestamp=a.timestamp};
A4.prototype.reset=function(){this.timestamp=this.Je=0};
B4.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.C[b][c].timestamp=a};
B4.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.C[b][c];a=0==d.Je?a+"_":a+String.fromCharCode(d.Je)}a+="\n"}return a};
B4.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.C[b][c].reset();this.B=a;this.o=0;this.A=this.row=1};
var FDa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],GDa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],HDa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],IDa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];H4.prototype.reset=function(a,b){this.D=b;this.style.set(2);this.A=this.F;this.C=this.G;this.o=this.A;var c=(a<<2)+(b<<1);this.F.reset(c);this.G.reset(c);this.H.reset((a<<2)+(b<<1)+1)};
w4.prototype.reset=function(a){this.D=a;this.o.clear();this.B=this.C;this.C.reset(a,0);this.F.reset(a,1)};g.t(J4,g.L);J4.prototype.reset=function(){};g.t(K4,J4);K4.prototype.reset=function(){this.H={};this.A=this.o=null;this.G=!0};
K4.prototype.B=function(a,b){var c=a.firstChild;c.getAttribute("format");b=b||0;Number.isFinite(b);c=Array.from(c.childNodes);c=g.r(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.r(e),c=e.next();!c.done;c=e.next())if(c=c.value,1==c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var k=this.C,l={},m=c.getAttribute("p");m&&g.Oa(l,this.C[m]);m=M4(c,"b");null!=m&&(l.bold=
m);m=M4(c,"i");null!=m&&(l.eg=m);m=M4(c,"u");null!=m&&(l.underline=m);m=N4(c,"et");null!=m&&(l.charEdgeStyle=m);m=N4(c,"of");null!=m&&(l.offset=m);m=P4(c,"bc");null!=m&&(l.background=m);m=P4(c,"ec");null!=m&&(l.qA=m);m=P4(c,"fc");null!=m&&(l.color=m);m=N4(c,"fs");null!=m&&0!=m&&(l.fontFamily=m);m=L4(c,"sz");void 0!=m&&(l.fontSizeIncrement=m/100-1);m=L4(c,"bo");void 0!=m&&(l.backgroundOpacity=m/255);m=L4(c,"fo");void 0!=m&&(l.textOpacity=m/255);m=N4(c,"rb");null!=m&&(l.Nn=m);c=N4(c,"hg");null!=c&&
(l.D4=c);k[d]=l;break;case "ws":d=c.getAttribute("id");this.K[d]=NDa(this,c);break;case "wp":d=c.getAttribute("id"),this.J[d]=ODa(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.r(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "w":this.o=PDa(this,d,e,!1);g.M(this,this.o);(d=this.H[this.o.id])&&d.end>this.o.start&&(d.end=this.o.start);this.H[this.o.id]=this.o;c.push(this.o);break;case "p":var n=e;k=[];l=d.getAttribute("w")||this.D;m=!!M4(d,"a");n=(L4(d,
"t")||0)+n;var p=L4(d,"d")||5E3;m||(!this.G&&this.A&&this.A.windowId==l&&this.A.end>n&&(this.A.end=n),this.A&&"\n"==this.A.text&&(this.A.text=""));var q=m?6:5,u=this.C[d.getAttribute("p")],w=d.childNodes;w.length&&(this.G=null!=d.getAttribute("d"));for(var D=0;D<w.length;D++){var F=w[D];0<D&&(m=!0);var I=void 0;1==F.nodeType&&(I=F);if(I&&"s"==I.tagName)if((F=this.C[I.getAttribute("p")])&&1==F.Nn){F=n;var O=p,na=l,Ia=m,Aa=q;var Ta=I;var $a=w[D+1];var wc=w[D+2],Lb=w[D+3];Ta.getAttribute("p");L4(Ta,
"t");L4($a,"t");L4(wc,"t");L4(Lb,"t");I=g.le("RUBY");Ta=Ta.textContent;var Ld=g.le("SPAN");Ld.innerText=Ta;I.appendChild(Ld);$a.getAttribute("p");Ld=g.le("RP");Ta=$a.textContent;Ld.innerText=Ta;I.appendChild(Ld);$a=this.C[wc.getAttribute("p")];Ta=wc.textContent;wc=g.le("RT");wc.innerText=Ta;I.appendChild(wc);if(4==$a.Nn||6==$a.Nn)g.Yh(I,"ruby-position","over"),g.Yh(I,"-webkit-ruby-position","before");else if(5==$a.Nn||7==$a.Nn)g.Yh(I,"ruby-position","under"),g.Yh(I,"-webkit-ruby-position","after");
Lb.getAttribute("p");Ta=Lb.textContent;Lb=g.le("RP");Lb.innerText=Ta;I.appendChild(Lb);F=new r4(F,O,Aa,na,I,Ia,null);D+=3}else Lb=I,F=n,O=p,na=l,Ia=m,Aa=q,I=Lb.textContent?Lb.textContent:"",Ta=this.C[Lb.getAttribute("p")],Lb=L4(Lb,"t")||0,F=new r4(F+Lb,O-Lb,Aa,na,I,Ia,Ta);else F=new r4(n,p,q,l,F.textContent||"",m,u);k.push(F);this.A=F}if(0<k.length)for(k[0].windowId==this.D&&(this.o=PDa(this,d,e,!0),g.M(this,this.o),c.push(this.o)),d=g.r(k),k=d.next();!k.done;k=d.next())k=k.value,k.windowId=this.o.id,
l=this.o,g.M(l,k),l.A.push(k),c.push(k)}e=c}else e=[];return e};g.t(Q4,u4);Q4.prototype.kt=function(a){var b=this.D.A;u4.prototype.kt.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.A==e)var d=f;else{d={};g.Oa(d,c.A);g.Oa(d,eEa);var e=c.A;var f=d}yDa(this,c,d)}};
var eEa={RL:!0};g.t(R4,zDa);R4.prototype.D=function(a,b,c,d,e){if(c<d){var f="_"+t4++;c=c/1E3-this.G;d=d/1E3-this.G;a=new s4(c,d-c,5,f,{textAlign:0,kh:0,fg:2.5*b,fi:5.33*a});e=new r4(c,d-c,5,f,e);this.C.push(a);this.C.push(e)}};
g.t(U4,J4);U4.prototype.B=function(a){a=new R4(a,a.byteLength,this.A);if(QDa(a)){for(;a.o<a.A.byteLength;)for(0==a.version?a.B=T4(a)*(1E3/45):1==a.version&&(a.B=4294967296*T4(a)+T4(a)),a.F=S4(a);0<a.F;a.F--){var b=S4(a),c=S4(a),d=S4(a);b&4&&(b&3)==this.track&&(0==this.track||1==this.track)&&(b=this.o,b.o.push({time:a.B,type:this.track,lA:c,mA:d,order:b.o.length}))}EDa(this.o,a);return a.C}return[]};
U4.prototype.reset=function(){this.o.clear()};g.t(V4,u4);g.h=V4.prototype;g.h.AF=function(){g.Ev(this.ka)};
g.h.sT=function(){g.Mr(this.element,"ytp-rollup-mode");this.tj(this.Ia,!0)};
g.h.sB=function(){return this.H?this.M:this.L};
g.h.tB=function(){return this.H?this.L:this.M};
g.h.tj=function(a,b){this.Ia=a;if(this.D.params.Mn){for(var c=0,d=0;d<this.G.length&&c<a.length;d++)this.G[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.G.concat(a.slice(c)));this.za=this.M;this.L=this.M=0;u4.prototype.tj.call(this,a);WDa(this,b);u4.prototype.tj.call(this,a)}else u4.prototype.tj.call(this,a)};g.t(W4,J4);
W4.prototype.B=function(a,b){for(var c=[],d=a.split(fEa),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!gEa.test(f)){var l=i5.exec(f);if(l&&4<=l.length){var m=X4(l[1]),n=X4(l[2])-m;m+=k;var p,q=p=void 0,u=void 0,w=void 0,D=l[3];l={textAlign:2};D=g.r(D?D.split(" "):[]);for(var F=D.next();!F.done;F=D.next())if(F=F.value.split(":"),2==F.length){var I=F[1];switch(F[0]){case "line":F=I.split(",");F[0].endsWith("%")&&(w=F[0],l.fi=Number.parseInt(w,10),2==F.length&&(u=F[1].trim()));break;case "position":F=I.split(",");
q=F[0];l.fg=Number.parseInt(q,10);2==F.length&&(p=F[1].trim());break;case "align":switch(I){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}w||(l.fi=100,u||(u="end"));if(!q)switch(l.textAlign){case 0:l.fg=0;break;case 1:l.fg=100;break;default:l.fg=50}q=0;switch(u){case "center":q+=3;break;case "end":q+=6;break;default:q+=0}switch(p){case "line-left":q+=0;break;case "center":q+=1;break;case "line-right":q+=2;break;default:switch(l.textAlign){case 0:q+=
0;break;case 2:q+=1;break;case 1:q+=2}}l.kh=0>q||8<q?7:q;p=l;f=f.substring(i5.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");q=p;p=f;f={};if(0>p.indexOf("<")&&0>p.indexOf("&"))k=YDa(m,n,5,q),n=new r4(m,n,5,k.id,p,!1,g.dc(f)?void 0:f),c.push(k),c.push(n),g.M(k,n),k.A.push(n);else for(u=p.split(hEa),1==u.length?(p=5,q=YDa(m,n,p,q)):(w=p=6,q=Object.assign({ep:32},q),q=new s4(m,n,w,"_"+t4++,q)),c.push(q),w=m,l=0;l<u.length;l++)D=u[l],0==l%2?(F=g.zt("<html>"+D+"</html>"),F.getElementsByTagName("parsererror").length?
(I=F.createElement("span"),I.appendChild(F.createTextNode(D))):I=F.firstChild,XDa(this,w,n-(w-m),p,q,0<l,I,f,c)):w=X4(D)+k}i5.lastIndex=0}}return c};
var gEa=/^NOTE/,fEa=/(?:\r\n|\r|\n){2,}/,i5=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),hEa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.t(Y4,g.L);Y4.prototype.clear=function(){this.o&&this.o.dispose();this.o=null};
Y4.prototype.reset=function(){this.o&&this.o.reset()};
Y4.prototype.V=function(){this.clear();g.L.prototype.V.call(this)};g.t(a5,g.kV);g.h=a5.prototype;g.h.V=function(){if(this.G||this.Y){var a=g.cV(this.L);a&&a.Ql()}else cEa(this,!1);g.kV.prototype.V.call(this)};
g.h.Tn=function(){return this.ma?this.G||this.Y:b5(this)?!0:ZDa(this)};
g.h.load=function(){g.kV.prototype.load.call(this);this.H=this.player.getAudioTrack();if(this.A)this.o&&(this.ga.clear(),this.G?$Da(this,!0):3!=this.player.getPresentingPlayerType()&&this.A.Lv(this.o,"srv3",(0,g.B)(this.dU,this))),this.o&&!e5(this)?this.player.Ba("captionschanged",g4(this.o)):this.player.Ba("onCaptionsTrackListChanged");else{var a;this.ua?a=new p4(this.C.oa,this.player):this.za?a=new l4(this.D,this.C,this.player.getAudioTrack()):a=new q4(this.C.Pl,this.C.videoId,this.C.nh||this.D.nh||
g.NP(this.C,"yt:cc_default_lang")||this.D.xa,this.C.Ct,this.D);this.A=a;g.M(this,this.A);a.Mv((0,g.B)(this.cU,this))}};
g.h.unload=function(){this.G&&this.o?$Da(this,!1):(this.ia&&g.Fv(this.ia),g.$U(this.player,"captions"),this.K=[],this.A&&this.A.gi(),this.ga.clear(),this.J&&g.XU(this.player,this.J),this.ay());g.kV.prototype.unload.call(this);var a=g.Z(this.player.app);a&&a.B&&g.wQ(a.B.C);this.player.Ba("captionschanged",{})};
g.h.cU=function(){var a;this.M||ZDa(this)?a=d5(this,this.M):b5(this)&&(a=c5(this));if(this.G||this.Y){for(var b=i4(this.A.A,!0),c=[],d=0;d<b.length;d++){var e=b[d],f={kind:"subtitles",label:g.KO(e),srclang:h4(e),id:e.toString()};this.Y||(f.src=this.A.Am(e,"vtt"));e==a&&(f["default"]=1);c.push(g.je("TRACK",f))}g.cV(this.L).Kl(c);a=g.cV(this.L).sa();this.ya&&this.Z.R(a.textTracks,"change",this.eU)}else!this.o&&a&&g5(this,a),this.player.Ba("onCaptionsTrackListChanged"),this.player.Ba("onApiChange")};
g.h.eU=function(){for(var a=g.cV(this.L).sa().textTracks,b=null,c=0;c<a.length;c++)if("showing"==a[c].mode)a:{b=i4(this.A.A,!0);for(var d=0;d<b.length;d++)if(b[d].toString()==a[c].id){b=b[d];break a}b=null}(this.loaded?this.o:null)!=b&&g5(this,b,!0)};
g.h.ZV=function(){!this.o&&this.G||this.unload()};
g.h.dU=function(a,b,c,d){if(a){this.A.lF()&&(this.K=[],g.$U(this.L,"captions"),this.ea.dk(),this.ga.reset());var e=this.ga;c=c||0;d=d||0;if(!g.x(a)){var f=new DataView(a);if(8<=f.byteLength&&1718909296==f.getUint32(4)&&(f=g.nJ(f,0,1835295092),a=a.slice(f.dataOffset,f.dataOffset+f.size),!RDa(a))){a=new Uint8Array(a);f=[];for(var k=0,l=0;k<a.length;){var m=a[k++];if(128>m)f[l++]=String.fromCharCode(m);else if(191<m&&224>m){var n=a[k++];f[l++]=String.fromCharCode((m&31)<<6|n&63)}else if(239<m&&365>m){n=
a[k++];var p=a[k++],q=a[k++];m=((m&7)<<18|(n&63)<<12|(p&63)<<6|q&63)-65536;f[l++]=String.fromCharCode(55296+(m>>10));f[l++]=String.fromCharCode(56320+(m&1023))}else n=a[k++],p=a[k++],f[l++]=String.fromCharCode((m&15)<<12|(n&63)<<6|p&63)}a=f.join("")}}if(a)try{if(g.x(a)){if("WEBVTT"==a.substring(0,6)){b=a;var u=c;e.o||(e.o=new W4);var w=e.o.B(b,u);.01>Math.random()&&g.mF(Error("Deprecated subtitles format in web player: WebVTT"));var D=w}else b:{w=a;u=g.zt(w);if(!u||!u.firstChild){var F=Error("Invalid caption track data");
F.params=w;throw F;}if("timedtext"==u.firstChild.tagName){if(3==parseInt(u.firstChild.getAttribute("format"),10)){if(!e.o){w={};var I=h4(b);I&&(w.lang=I,dEa.test(I)&&(w.ug=1));e.o=new K4(w,e.A)}D=e.o.B(u,c);break b}var O=Error("Unsupported subtitles format in web player (Format2)");O.params=w;throw O;}if("transcript"==u.firstChild.tagName){var na=Error("Unsupported subtitles format in web player (Format1)");na.params=w;throw na;}var Ia=Error("Invalid caption track data");Ia.params=w;throw Ia;}var Aa=
D}else{D=a;u=c;I=d;if(!RDa(D))throw Error("Invalid binary caption track data");e.o||(e.o=new U4(I,b));Aa=e.o.B(D,u)}var Ta=Aa}catch($a){g.kF($a),e.clear(),Ta=[]}else Ta=[];g.XU(this.player,Ta);!this.M||this.Y||e5(this)||g.nO(this.D)||g.oO(this.D)||(g.Fv(this.ia),Ta=tDa({kh:0,fg:5,fi:5,Mn:2,textAlign:0,ug:0,lang:"en"}),this.P=[Ta],e=["Click "," for settings"],this.ka||(Aa=new g.eQ(g.Eta()),g.M(this,Aa),this.ka=Aa.element),Aa=Ta.end-Ta.start,(b=g.KO(this.o))&&this.P.push(new r4(Ta.start,Aa,0,Ta.id,
b)),this.P.push(new r4(Ta.start,Aa,0,Ta.id,e[0]),new r4(Ta.start,Aa,0,Ta.id,this.ka,!0),new r4(Ta.start,Aa,0,Ta.id,e[1],!0)),g.XU(this.player,this.P),g.Dv(this.ia));!this.M||this.Y||e5(this)||(f5(this,"module-enabled",!0),this.H&&(this.H.o=this.o),(Ta=g.Z(this.player.app))&&Ta.B&&g.wQ(Ta.B.C));this.M=!1}};
g.h.MN=function(a){this.K.push(a);this.ea.dk()};
g.h.NN=function(a){g.eb(this.K,a);this.A instanceof p4&&this.A.F&&g.ZU(this.player,[a]);this.ea.dk()};
g.h.YU=function(a){if(a instanceof s4){var b=this.W[a.id];b&&b.D!=a&&(b.dispose(),delete this.W[a.id],b=null);b||(b=aEa(this,a))&&(this.W[a.id]=b)}else b=a.windowId,this.aa[b]||(this.aa[b]=[]),this.aa[b].push(a)};
g.h.fV=function(){bEa(this,this.P);this.P=null};
g.h.zG=function(){this.ea.stop();g.ec(this.aa);this.K.sort(g.kR);var a=this.K;if(this.J){var b=(0,g.se)(a,function(c){return-1==this.J.indexOf(c)},this);
b.length&&(a=b)}(0,g.E)(a,this.YU,this);g.Nb(this.W,function(c,d){this.aa[d]?(c.element.parentNode||g.bV(this.player,c.element,4),c.tj(this.aa[d])):(c.dispose(),delete this.W[d])},this)};
g.h.kV=function(){Z4(this,{},!0)};
g.h.SK=function(){var a=h5.Ub;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.eg?3:a.bold?1:a.eg?2:0,textOpacity:a.textOpacity,windowColor:h5.windowColor,windowOpacity:h5.windowOpacity};var b=$4(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.h.DG=function(a,b){var c={};g.Oa(c,$4(this,"display-settings"));g.Oa(c,a);Z4(this,c,b);this.player.U("captionssettingschanged")};
g.h.ay=function(){!this.G&&this.loaded&&(g.Nb(this.W,function(a,b){a.dispose();delete this.W[b]},this),this.zG())};
g.h.Ic=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.Kd(b,-2,4);this.DG({fontSizeIncrement:c});return c;case "reload":b&&!this.G&&g5(this,this.o,!0);break;case "stickyLoading":void 0!=b&&this.D.Ob&&f5(this,"module-enabled",!!b);break;case "track":if(!this.A)return{};if(b){if(this.G)break;if(!g.Ka(b))break;if(g.dc(b)){g5(this,null,!0);break}for(var d=i4(this.A.A,!0),e=0;e<d.length;e++){var f=d[e];f.A!=b.languageCode||c&&f.B!=b.languageName||(c=b.translationLanguage?nDa(f,b.translationLanguage):
f)}!c||c==this.o&&this.loaded||g5(this,c,!0)}else return this.loaded&&this.o&&!e5(this)?g4(this.o):{};return"";case "tracklist":return this.A?(0,g.K)(i4(this.A.A,!(!b||!b.includeAsr)),function(k){return g4(k)}):[];
case "translationLanguages":return this.A?this.A.D:[];case "sampleSubtitles":this.G||void 0==b||cEa(this,!!b)}};
g.h.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.D.Ob&&a.push("stickyLoading");return a};
g.h.Og=function(){var a=this.o;return a?{cc:a.F}:{}};
g.h.qG=function(){this.loaded&&this.o&&!e5(this)?(f5(this,"module-enabled",!1),this.unload(),b5(this,!0)&&g5(this,c5(this),!1)):g5(this,e5(this)||!this.o?d5(this,!0):this.o,!0)};
g.h.uQ=function(){var a=e5(this);b5(this,a)?g5(this,this.player.getAudioTrack().xp,!1):this.C.captionTracks.length&&(this.loaded&&this.unload(),this.Tn()&&(a?g5(this,d5(this),!1):this.load()))};g.VZ.captions=a5;})(_yt_player);
