(function(g){var window=this;var iEa=function(a,b,c){a.o.has(b);a.o.add(b);g.Of(c,function(){g.lya(a,b)})},j5=function(a,b,c){var d=b.Aa();
g.U(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.hd(c?c:"mqdefault.jpg");var f=b instanceof g.yP&&b.lengthSeconds?g.JV(b.lengthSeconds):null,k=!!e;e=k&&"RD"==(new g.mR(e.substr(0,2),e.substr(2))).type;var l=b instanceof g.yP?b.Da:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:b.author,aria_label:b.Ll||g.uV("Watch $TITLE",{TITLE:b.title}),duration:f,url:b.Cm(),is_live:l,is_list:k,is_mix:e,background:c?"background-image: url("+
c+")":""};b instanceof g.oR&&(d.playlist_length=b.getLength());a.update(d)},k5=function(a,b){g.jQ.call(this,{I:"div",
da:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.player=a;this.created=!1},l5=function(a){g.W.call(this,{I:"div",
da:["ytp-upnext","ytp-player-content"],T:{"aria-label":"{{aria_label}}"},O:[{I:"div",N:"ytp-cued-thumbnail-overlay-image",T:{style:"{{background}}"}},{I:"span",N:"ytp-upnext-top",O:[{I:"span",N:"ytp-upnext-header",ca:"Up Next"},{I:"span",N:"ytp-upnext-title",ca:"{{title}}"},{I:"span",N:"ytp-upnext-author",ca:"{{author}}"}]},{I:"a",N:"ytp-upnext-autoplay-icon",T:{role:"button",href:"{{url}}","aria-label":"Play next video"},O:[{I:"svg",T:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
O:[{I:"circle",N:"ytp-svg-autoplay-circle",T:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{I:"circle",N:"ytp-svg-autoplay-ring",T:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{I:"path",N:"ytp-svg-fill",T:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{I:"span",N:"ytp-upnext-bottom",O:[{I:"span",N:"ytp-upnext-cancel"},{I:"span",N:"ytp-upnext-paused",
ca:"Autoplay is paused"}]}]});this.G=null;var b=this.o["ytp-upnext-cancel"];this.G=new g.W({I:"button",da:["ytp-upnext-cancel-button","ytp-button"],T:{tabindex:"0","aria-label":"Cancel autoplay"},ca:"Cancel"});g.M(this,this.G);this.G.X("click",this.CQ,this);this.G.A(b);this.B=a;this.M=this.o["ytp-svg-autoplay-ring"];this.J=this.H=this.D=this.F=null;this.K=new g.V(this.cp,5E3,this);g.M(this,this.K);this.L=0;this.R(this.o["ytp-upnext-autoplay-icon"],"click",this.FS);this.hE();this.R(a,"autonavvisibility",
this.hE);this.R(a,"mdxnowautoplaying",this.UR);this.R(a,"mdxautoplaycanceled",this.VR);this.R(a,"mdxautoplayupnext",this.CG);3==this.B.getPresentingPlayerType()&&(a=(a=g.PU(g.KU(this.B)))?a.QK():null)&&this.CG(a)},m5=function(a,b){if(!a.D){g.BF("a11y-announce","Up Next "+a.F.title);
a.L=g.SH();a.D=new g.V((0,g.B)(a.it,a,b),25);a.it(b);var c=b||g.Y(a.B).experiments.A("autoplay_time")||1E4;a.B.Ba("onAutonavCoundownStarted",c)}g.Mr(a.element,"ytp-upnext-autoplay-paused")},o5=function(a){n5(a);
a.L=g.SH();a.it();g.T(a.element,"ytp-upnext-autoplay-paused")},n5=function(a){a.D&&(a.D.dispose(),a.D=null)},p5=function(a,b){b=void 0===b?!1:b;
if(g.Y(a.B).experiments.o("autonav_notifications")&&b&&window.Notification&&document.hasFocus){var c=Notification.permission;"default"==c?Notification.requestPermission():"granted"!=c||document.hasFocus()||(c=a.F.Aa(),a.cp(),a.H=new Notification("Up Next",{body:c.title,icon:c.hd()}),a.J=a.R(a.H,"click",a.wS),a.K.start())}n5(a);a.B.nextVideo(!1,b)},jEa=function(a){k5.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.B=new g.W({I:"div",N:"ytp-subscribe-card",O:[{I:"img",N:"ytp-author-image",T:{src:b.Tk}},{I:"div",N:"ytp-subscribe-card-right",O:[{I:"div",N:"ytp-author-name",ca:b.author},{I:"div",N:"html5-subscribe-button-container"}]}]});g.M(this,this.B);this.B.A(this.element);this.D=new g.x_("Subscribe",null,"Unsubscribe",null,!0,!1,b.hi,b.subscribed,"trailer-endscreen",null,null,a);g.M(this,this.D);this.D.A(this.B.o["html5-subscribe-button-container"]);this.hide()},q5=function(a){var b=
g.Y(a),c=g.pM||g.Tf?{style:"will-change: opacity"}:void 0,d=b.o,e=["ytp-videowall-still"];
b.A&&e.push("ytp-videowall-show-text");g.W.call(this,{I:"a",da:e,T:{href:"{{url}}",target:d?b.F:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},O:[{I:"div",N:"ytp-videowall-still-image",T:{style:"{{background}}"}},{I:"span",N:"ytp-videowall-still-info",O:[{I:"span",N:"ytp-videowall-still-info-bg",O:[{I:"span",N:"ytp-videowall-still-info-content",T:c,O:[{I:"span",N:"ytp-videowall-still-info-title",ca:"{{title}}"},{I:"span",N:"ytp-videowall-still-info-author",
ca:"{{author_and_views}}"},{I:"span",N:"ytp-videowall-still-info-live",ca:"Live"},{I:"span",N:"ytp-videowall-still-info-duration",ca:"{{duration}}"}]}]}]},{I:"span",da:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],O:[{I:"span",N:"ytp-videowall-still-listlabel-icon"},"Playlist",{I:"span",N:"ytp-videowall-still-listlabel-length",O:[" (",{I:"span",ca:"{{playlist_length}}"},")"]}]},{I:"span",da:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],O:[{I:"span",
N:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{I:"span",N:"ytp-videowall-still-listlabel-length",ca:" (50+)"}]}]});this.G=d;this.B=a;this.D=null;this.F=new g.vH(this);g.M(this,this.F);this.X("click",this.J);this.X("keypress",this.K);this.F.R(a,"videodatachange",this.H);g.Y(a).ea&&iEa(a.app.ka,this.element,this);this.H()},r5=function(a){k5.call(this,a,"videowall-endscreen");
this.L=a;this.H=0;this.D=[];this.J=this.F=this.G=null;this.K=this.aa=!1;this.Y=null;this.Z=new g.vH(this);g.M(this,this.Z);this.M=new g.V(g.Na(g.T,this.element,"ytp-show-tiles"),0);g.M(this,this.M);var b=new g.W({I:"button",da:["ytp-button","ytp-endscreen-previous"],T:{"aria-label":"Previous"},O:[g.CV()]});g.M(this,b);b.A(this.element);b.X("click",this.sO,this);this.P=new g.eQ({I:"div",N:"ytp-endscreen-content"});g.M(this,this.P);this.P.A(this.element);b=new g.W({I:"button",da:["ytp-button","ytp-endscreen-next"],
T:{"aria-label":"Next"},O:[g.DV()]});g.M(this,b);b.A(this.element);b.X("click",this.rO,this);this.B=new l5(a);g.M(this,this.B);g.bV(this.player,this.B.element,4);this.hide()},s5=function(a){return g.dV(a.player)&&a.cA()&&!a.J},kEa=function(a,b){return(0,g.K)(b.suggestions,function(c){c=g.VV(g.Y(a.L),c);
g.M(a,c);return c})},t5=function(a){var b=a.dg();
b!=a.aa&&(a.aa=b,a.player.U("autonavvisibility"))},u5=function(a){g.kV.call(this,a);
this.o=null;this.A=new g.vH(this);g.M(this,this.A);this.C=g.Y(a);lEa(a)?this.o=new r5(this.player):this.C.Ia?this.o=new jEa(this.player):this.o=new k5(this.player);g.M(this,this.o);g.bV(this.player,this.o.element,4);this.zF();this.A.R(a,"videodatachange",this.zF,this);this.A.R(a,g.lR("endscreen"),this.GN,this);this.A.R(a,"crx_endscreen",this.HN,this)},lEa=function(a){a=g.Y(a);
return a.Ga&&!a.Ia};
g.t(k5,g.jQ);k5.prototype.create=function(){this.created=!0};
k5.prototype.destroy=function(){this.created=!1};
k5.prototype.cA=function(){return!1};
k5.prototype.dg=function(){return!1};g.t(l5,g.W);g.h=l5.prototype;g.h.cp=function(){this.H&&(this.K.stop(),this.Ka(this.J),this.J=null,this.H.close(),this.H=null)};
g.h.hE=function(){g.iQ(this,this.B.dg())};
g.h.wS=function(){window.focus();this.cp()};
g.h.hide=function(){g.W.prototype.hide.call(this)};
g.h.it=function(a){a=a||g.Y(this.B).experiments.A("autoplay_time")||1E4;var b=Math.min(g.SH()-this.L,a);a=Math.min(b/a,1);this.M.setAttribute("stroke-dashoffset",-211*(a+1));1<=a&&3!=this.B.getPresentingPlayerType()?p5(this,!0):this.D&&this.D.start()};
g.h.FS=function(a){!g.xe(this.G.element,g.jH(a))&&g.XV(a,this.B)&&p5(this)};
g.h.CQ=function(){g.MU(this.B,!0)};
g.h.UR=function(a){this.B.getPresentingPlayerType();this.show();m5(this,a)};
g.h.CG=function(a){this.B.getPresentingPlayerType();this.F&&this.F.Aa().videoId==a.Aa().videoId||(this.F=a,j5(this,a,"hqdefault.jpg"))};
g.h.VR=function(){this.B.getPresentingPlayerType();n5(this);this.hide()};
g.h.V=function(){n5(this);this.cp();g.W.prototype.V.call(this)};g.t(jEa,k5);g.t(q5,g.W);q5.prototype.al=function(){g.fV(this.B,this.element);var a=this.D.Aa().videoId,b=this.D.getPlaylistId();g.M0(this.B.app,a,this.D.Id,b,void 0,void 0,void 0)};
q5.prototype.J=function(a){g.XV(a,this.B,this.G,this.D.Id||void 0)&&this.al()};
q5.prototype.K=function(a){switch(a.keyCode){case 13:case 32:g.oH(a)||(this.al(),g.nH(a))}};
q5.prototype.H=function(){var a=this.B.getVideoData(),b=g.Y(this.B);this.G=a.Lc?!1:b.o};g.t(r5,k5);g.h=r5.prototype;g.h.create=function(){k5.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.G=kEa(this,a),this.F=a);this.Xg();this.Z.R(this.player,"appresize",this.Xg);this.Z.R(this.player,"onVideoAreaChange",this.Xg);this.Z.R(this.player,"videodatachange",this.tO);this.Z.R(this.player,"autonavchange",this.Zv);this.Z.R(this.player,"autonavcancel",this.qO);a=this.F.autonavState;a!=this.Y&&this.Zv(a);this.Z.R(this.element,"transitionend",this.fU)};
g.h.destroy=function(){g.xH(this.Z);g.Qf(this.D);this.D=[];this.G=null;k5.prototype.destroy.call(this);g.Mr(this.element,"ytp-show-tiles");this.M.stop();this.Y=this.F.autonavState};
g.h.cA=function(){return 1!=this.F.autonavState};
g.h.show=function(){k5.prototype.show.call(this);g.Mr(this.element,"ytp-show-tiles");g.Y(this.player).A?g.Ev(this.M):this.M.start();(this.K||this.J&&this.J!=this.F.clientPlaybackNonce)&&g.MU(this.player,!1);s5(this)?(t5(this),2==this.F.autonavState?g.Y(this.player).experiments.o("fast_autonav_in_background")&&3==this.player.getVisibilityState()?p5(this.B,!0):m5(this.B):3==this.F.autonavState&&o5(this.B)):(g.MU(this.player,!0),t5(this))};
g.h.hide=function(){k5.prototype.hide.call(this);o5(this.B);t5(this)};
g.h.fU=function(a){g.jH(a)==this.element&&this.Xg()};
g.h.Xg=function(){if(this.G&&this.G.length){g.T(this.element,"ytp-endscreen-paginate");var a=g.VU(this.L,!0),b=g.uQ(this.L);b&&(b=b.bd()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.G.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var p=b/2,q=e/2,u=b<=f-2&&n>=q*m,w=e<=k-2&&n>=p*m;if((p+1)/q*d/c>c/(p/(q+1)*d)&&w)n-=p*m,e+=2;else if(u)n-=q*m,b+=2;else if(w)n-=p*m,e+=2;else break}d=
!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;m*=g.Kd(a.width/m||1,1,1.21);n*=g.Kd(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.P.element;g.pi(a,m,n);g.Yh(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});c=this.B;f=this.G[0];c.F=f;j5(c,f,"hqdefault.jpg");g.U(this.element,"ytp-endscreen-takeover",s5(this));t5(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(k=0;k<e;k++)if(p=c,q=0,d&&f>=b-2&&k>=e-
2?q=1:0==k%2&&0==f%2&&(2>k&&2>f?0==k&&0==f&&(q=2):q=2),p=g.Md(p+this.H,l),0!=q){u=this.D[c];u||(u=new q5(this.player),this.D[c]=u,a.appendChild(u.element));w=Math.floor(n*k/e);var D=Math.floor(m*f/b),F=Math.floor(n*(k+q)/e)-w-4,I=Math.floor(m*(f+q)/b)-D-4;g.ei(u.element,D,w);g.pi(u.element,I,F);g.Yh(u.element,"transitionDelay",(k+f)/20+"s");g.U(u.element,"ytp-videowall-still-mini",1==q);g.U(u.element,"ytp-videowall-still-large",2<q);q=u;p=this.G[p];q.D!=p&&(q.D=p,j5(q,p,g.Kr(q.element,"ytp-videowall-still-large")?
"hqdefault.jpg":"mqdefault.jpg"),u=(p=p.Id)&&p.itct)&&(p=q.B,g.Y(p).ea&&(q=q.element,p.app.ka.o.has(q),u&&(q.visualElement=g.qI(u))));c++}g.U(this.element,"ytp-endscreen-paginate",c<l);for(b=this.D.length-1;b>=c;b--)e=this.D[b],g.re(e.element),g.Pf(e);this.D.length=c}};
g.h.tO=function(){var a=this.player.getVideoData();this.F!=a&&(this.H=0,this.G=kEa(this,a),this.F=a,this.Xg())};
g.h.rO=function(){this.H+=this.D.length;this.Xg()};
g.h.sO=function(){this.H-=this.D.length;this.Xg()};
g.h.RM=function(){return!!this.B.D};
g.h.Zv=function(a){1==a?(this.K=!1,this.J=this.F.clientPlaybackNonce,n5(this.B),this.C&&this.Xg()):(this.K=!0,this.C&&s5(this)&&(2==a?m5(this.B):3==a&&o5(this.B)))};
g.h.qO=function(a){if(a){for(a=0;a<this.D.length;a++)g.gV(this.L,this.D[a].element,!0);this.Zv(1)}else this.J=null,this.K=!1;this.Xg()};
g.h.dg=function(){return this.C&&s5(this)};g.t(u5,g.kV);g.h=u5.prototype;g.h.Tn=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!lEa(this.player)||b;a=a.qd;var c=g.t0(this.player.app);return b&&!a&&!c};
g.h.dg=function(){return this.o.dg()};
g.h.NM=function(){return this.dg()?this.o.RM():!1};
g.h.V=function(){g.$U(this.player,"endscreen");g.kV.prototype.V.call(this)};
g.h.load=function(){g.kV.prototype.load.call(this);this.o.show()};
g.h.unload=function(){g.kV.prototype.unload.call(this);this.o.hide();this.o.destroy()};
g.h.GN=function(a){this.Tn()&&(this.o.created||this.o.create(),"load"==a.getId()&&this.load())};
g.h.HN=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.zF=function(){g.$U(this.player,"endscreen");var a=Math.max(1E3*(this.player.getVideoData().lengthSeconds-10),0);a=new g.jR(a,0x8000000000000,{id:"preload",namespace:"endscreen"});g.M(this,a);var b=new g.jR(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.M(this,b);g.XU(this.player,[a,b])};g.VZ.endscreen=u5;})(_yt_player);
